# Generated by Django 6.0.3 on 2026-03-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Zdjęcie hero')),
            ],
            options={
                'verbose_name': 'Ustawienia strony',
                'verbose_name_plural': 'Ustawienia strony',
            },
        ),
    ]
