# Generated by Django 6.0.3 on 2026-03-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_body',
            field=models.TextField(default='Nasza wypożyczalnia sprzętu rehabilitacyjnego powstała z prostej potrzeby – każdy zasługuje na wygodny dostęp do profesjonalnego sprzętu, bez zbędnych formalności i w przystępnej cenie. Oferujemy indywidualne podejście do każdego klienta i doradzimy w wyborze odpowiedniego sprzętu.', verbose_name='O nas – treść'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_check_items',
            field=models.JSONField(blank=True, default=list, help_text='Lista punktów, np. ["Wieloletnie doświadczenie", "Konkurencyjne ceny"]', verbose_name='O nas – lista cech'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='O nas – zdjęcie'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_lead',
            field=models.CharField(default='Od lat pomagamy pacjentom i ich rodzinom w powrocie do sprawności.', max_length=300, verbose_name='O nas – lead'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat1_label',
            field=models.CharField(default='Zadowolonych klientów', max_length=60, verbose_name='Statystyka 1 – opis'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat1_number',
            field=models.CharField(default='500+', max_length=20, verbose_name='Statystyka 1 – liczba'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat2_label',
            field=models.CharField(default='Modeli sprzętu', max_length=60, verbose_name='Statystyka 2 – opis'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat2_number',
            field=models.CharField(default='100+', max_length=20, verbose_name='Statystyka 2 – liczba'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_tag',
            field=models.CharField(default='O nas', max_length=60, verbose_name='O nas – etykieta'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='Jesteśmy z Tobą, gdy zdrowie tego wymaga.', max_length=200, verbose_name='O nas – tytuł'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_note',
            field=models.CharField(default='Zapraszamy do siedziby', max_length=60, verbose_name='Nota przy adresie'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='kontakt@medrent.pl', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_note',
            field=models.CharField(default='Odpowiadamy w 24h', max_length=60, verbose_name='Nota przy emailu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+48 000 000 000', max_length=30, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone_hours',
            field=models.CharField(default='Pon–Pt: 8:00–18:00', max_length=60, verbose_name='Godziny telefoniczne'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(default='MEDRENT', max_length=60, verbose_name='Tekst nad tytułem'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(default='Profesjonalny sprzęt rehabilitacyjny – wypożycz, kup lub zamów z dostawą', max_length=220, verbose_name='Podtytuł'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title1',
            field=models.CharField(default='Wypożyczalnia', max_length=80, verbose_name='Tytuł – linia 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title2',
            field=models.CharField(default='Medyczna', max_length=80, verbose_name='Tytuł – linia 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service1_desc',
            field=models.CharField(default='Szeroki wybór sprzętu rehabilitacyjnego na dni, tygodnie lub miesiące', max_length=200, verbose_name='Usługa 1 – opis'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service1_title',
            field=models.CharField(default='Wypożycz', max_length=80, verbose_name='Usługa 1 – tytuł'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service2_desc',
            field=models.CharField(default='Sprawdzony sprzęt w atrakcyjnych cenach – nowy i używany', max_length=200, verbose_name='Usługa 2 – opis'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service2_title',
            field=models.CharField(default='Kup na własność', max_length=80, verbose_name='Usługa 2 – tytuł'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service3_desc',
            field=models.CharField(default='Przywozimy sprzęt pod Twoje drzwi – szybko i wygodnie', max_length=200, verbose_name='Usługa 3 – opis'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service3_title',
            field=models.CharField(default='Zamów dostawę', max_length=80, verbose_name='Usługa 3 – tytuł'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Zdjęcie tła'),
        ),
    ]
