# Generated by Django 6.0.3 on 2026-03-15 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_seo_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='kontakt@luma.pl', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(default='LUMA', max_length=60, verbose_name='Tekst nad tytułem'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Zdjęcie')),
                ('is_main', models.BooleanField(default=False, verbose_name='Zdjęcie główne')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Kolejność')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Zdjęcie produktu',
                'verbose_name_plural': 'Zdjęcia produktu',
                'ordering': ['-is_main', 'order'],
            },
        ),
    ]
