# Generated by Django 6.0.3 on 2026-03-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_product_image_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(help_text='Np. "polityka-prywatnosci" → /strony/polityka-prywatnosci/', unique=True, verbose_name='Slug (URL)')),
                ('content', models.TextField(help_text='Możesz używać HTML: <h2>, <p>, <ul>, <li>, <strong>, <a href="...">, itd.', verbose_name='Treść (HTML)')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description (SEO)')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='Pokaż w stopce')),
                ('footer_order', models.PositiveSmallIntegerField(default=0, verbose_name='Kolejność w stopce')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
            ],
            options={
                'verbose_name': 'Strona informacyjna',
                'verbose_name_plural': 'Strony informacyjne',
                'ordering': ['footer_order', 'title'],
            },
        ),
    ]
