# Generated by Django 6.0.3 on 2026-03-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_page_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone2_hours',
            field=models.CharField(blank=True, max_length=60, verbose_name='Telefon 2 – godziny'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone3',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone3_hours',
            field=models.CharField(blank=True, max_length=60, verbose_name='Telefon 3 – godziny'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+48 000 000 000', max_length=30, verbose_name='Telefon 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone_hours',
            field=models.CharField(default='Pon–Pt: 8:00–18:00', max_length=60, verbose_name='Telefon 1 – godziny'),
        ),
    ]
